In [123]:
from sklearn.datasets import load_iris



In [124]:
iris=load_iris()



In [125]:
from sklearn.model_selection import train_test_split



In [126]:
x_train,x_dev,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.4,random_state=0)



In [127]:
x_train.shape

(90, 4)

In [128]:
import lightgbm as lgb



In [129]:
train_data=lgb.Dataset(x_train,label=y_train)



In [130]:
dev_data=lgb.Dataset(x_dev,label=y_test)



In [131]:
params = {
    'task': 'train',
    'boosting_type': 'gbdt',  # 设置提升类型
    'objective': 'regression', # 目标函数
    'metric': {'l2', 'auc'},  # 评估函数
    'num_leaves': 31,   # 叶子节点数
    'learning_rate': 0.05,  # 学习速率
    'feature_fraction': 0.9, # 建树的特征选择比例
    'bagging_fraction': 0.8, # 建树的样本采样比例
    'bagging_freq': 5,  # k 意味着每 k 次迭代执行bagging
    'verbose': 1 # <0 显示致命的, =0 显示错误 (警告), >0 显示信息
}



In [132]:
lgb.cv(params,train_data)



{'l2-mean': [0.6487301142887211,
  0.6034486524317313,
  0.5630030883068236,
  0.5250914519944961,
  0.48784519140092913,
  0.4537388411702956,
  0.4240603961036012,
  0.3954541057050135,
  0.3693090659409847,
  0.3463045263696441,
  0.3212833618084948,
  0.29953288356017904,
  0.27928808235429436,
  0.26018125861844077,
  0.24339785905107875,
  0.22713083252154748,
  0.21290814066475075,
  0.20017397573124907,
  0.18794238611398895,
  0.17673487206622088,
  0.16537725791843155,
  0.15503003222074777,
  0.14582550756537396,
  0.13720230487064664,
  0.12941487066082077,
  0.1229065656524477,
  0.11711229344015979,
  0.11208255182157507,
  0.10701773743963264,
  0.10277471917218786,
  0.09805343102812268,
  0.0938151211328894,
  0.09001156646951874,
  0.08615116252223512,
  0.08304034634685588,
  0.0802756526818162,
  0.07767541457763269,
  0.07545019593193443,
  0.07329295607094041,
  0.07144315057515815,
  0.06922073790179965,
  0.06741389296026412,
  0.06520849264322329,
  0.063416748

In [133]:
cv_res=lgb.cv(params,train_data)



In [134]:
cv_res.get("auc_mean")

In [135]:
cv_res.get("auc-mean")

[0.9214285714285715,
 0.9633333333333333,
 0.9633333333333333,
 0.9657142857142859,
 0.9776190476190477,
 0.9976190476190476,
 0.9976190476190476,
 0.9976190476190476,
 0.9976190476190476,
 0.9976190476190476,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0]

In [136]:
len(cv_res.get("auc-mean"))

100

In [137]:
cv_res.get("auc-mean").index(1)

10

In [138]:
bst=lgb.train(params,train_data,valid_sets=[dev_data],early_stopping_rounds=10)

[1]	valid_0's l2: 0.579038	valid_0's auc: 1
Training until validation scores don't improve for 10 rounds.
[2]	valid_0's l2: 0.529096	valid_0's auc: 1
[3]	valid_0's l2: 0.488267	valid_0's auc: 1
[4]	valid_0's l2: 0.449075	valid_0's auc: 1
[5]	valid_0's l2: 0.411726	valid_0's auc: 1
[6]	valid_0's l2: 0.381408	valid_0's auc: 1
[7]	valid_0's l2: 0.354062	valid_0's auc: 1
[8]	valid_0's l2: 0.329398	valid_0's auc: 1
[9]	valid_0's l2: 0.307154	valid_0's auc: 1
[10]	valid_0's l2: 0.287094	valid_0's auc: 1
[11]	valid_0's l2: 0.266234	valid_0's auc: 1
Early stopping, best iteration is:
[1]	valid_0's l2: 0.579038	valid_0's auc: 1


In [139]:
bst.best_iteration

1

In [140]:
x_train,x_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.4,random_state=0)



In [141]:
x_input,x_dev,y_input,y_dev=train_test_split(x_train,y_train,test_size=0.1,random_state=0)

In [142]:
x_dev.shape

(9, 4)

In [143]:
cv_train=lgb.Dataset(x_train,label=y_train)

In [144]:
cv_res=lgb.cv(params,cv_train)

In [145]:
cv_res.get("auc-mean").index(1)

10

In [147]:
train_data=lgb.Dataset(x_input,label=y_input)
dev_data=lgb.Dataset(x_dev,label=y_dev)
bst=lgb.train(params,train_data,valid_sets=[dev_data],early_stop_rounds=10)

TypeError: train() got an unexpected keyword argument 'early_stop_rounds'

In [148]:
train_data=lgb.Dataset(x_input,label=y_input)
dev_data=lgb.Dataset(x_dev,label=y_dev)
bst=lgb.train(params,train_data,valid_sets=[dev_data],early_stopping_rounds=10)

[1]	valid_0's l2: 0.907221	valid_0's auc: 1
Training until validation scores don't improve for 10 rounds.
[2]	valid_0's l2: 0.831117	valid_0's auc: 1
[3]	valid_0's l2: 0.766044	valid_0's auc: 1
[4]	valid_0's l2: 0.718224	valid_0's auc: 1
[5]	valid_0's l2: 0.660871	valid_0's auc: 1
[6]	valid_0's l2: 0.608816	valid_0's auc: 1
[7]	valid_0's l2: 0.561748	valid_0's auc: 1
[8]	valid_0's l2: 0.519186	valid_0's auc: 1
[9]	valid_0's l2: 0.480694	valid_0's auc: 1
[10]	valid_0's l2: 0.44588	valid_0's auc: 1
[11]	valid_0's l2: 0.414969	valid_0's auc: 1
Early stopping, best iteration is:
[1]	valid_0's l2: 0.907221	valid_0's auc: 1


In [149]:
best_iter=bst.best_iteration
bst.save_model("iris_model.txt",num_iteration=best_iter)

In [150]:
pred=bst.predict(x_test,num_iteration=best_iter)

In [151]:
y_test.shape

(60,)

In [152]:
pred

array([1.00070547, 0.95308642, 0.90308642, 1.00070547, 0.90308642,
       1.00070547, 0.90308642, 0.95308642, 0.95308642, 0.95308642,
       0.95308642, 0.95308642, 0.95308642, 0.95308642, 0.95308642,
       0.90308642, 0.95308642, 0.95308642, 0.90308642, 0.90308642,
       1.00070547, 0.95308642, 0.95308642, 0.90308642, 1.00070547,
       0.90308642, 0.95308642, 0.95308642, 0.95308642, 0.90308642,
       1.00070547, 0.95308642, 0.90308642, 1.00070547, 1.00070547,
       0.95308642, 0.95308642, 1.00070547, 0.95308642, 0.95308642,
       1.00070547, 0.90308642, 1.00070547, 0.90308642, 0.90308642,
       0.95308642, 1.00070547, 1.00070547, 0.95308642, 1.00070547,
       0.95308642, 1.00070547, 1.00070547, 0.95308642, 1.00070547,
       0.95308642, 1.00070547, 1.00070547, 0.95308642, 1.00070547])

In [153]:
pred.shape

(60,)

In [154]:
params = {
    "objective":"multiclass",
    "num_class":3,
    "metics":"auc",
    "learning_rate":0.05,
}



In [156]:
params = {
    "objective":"multiclass",
    "num_class":3,
    "metics":"multi_logloss",
    "learning_rate":0.05,
}



In [157]:
new_cv=lgb.cv(params,cv_train)

LightGBMError: Multiclass objective and metrics don't match

In [158]:
params

{'objective': 'multiclass',
 'num_class': 3,
 'metics': 'multi_logloss',
 'learning_rate': 0.05}

In [159]:
params = {
    "objective":"multiclass",
    "num_class":3,
    "metric":"multi_logloss",
    "learning_rate":0.05,
}



In [160]:
new_cv=lgb.cv(params,cv_train)

In [161]:
nround=new_cv.get("multi_logloss-mean").index(min(new_cv.get("multi_logloss-mean")))

In [162]:
nround

99

In [163]:
bst=lgb.train(params,cv_train,num_boost_round=nround)

In [164]:
bst.best_iteration

0

In [165]:
bst.save_model("iris_model.txt",num_iteration=nround)

In [166]:
y_hat=bst.predict(x_test,num_iteration=99)
print(y_hat.shape)
from numpy import argmax
pred = [argmax(_p) for _p in y_hat]
print("test samples length={}".format(len(pred)))
accuracy=sum([1 if _p==_r else 0 for _p,_r in zip(pred,y_test)])/len(pred)

(60, 3)
test samples length=60


In [167]:
accuracy

0.9166666666666666

In [168]:
load_bst=lgb.Booster(params=params,train_set=cv_train,model_file="iris_model")

In [169]:
y_hat=load_bst.predict(x_test,num_iteration=99)
print(y_hat.shape)
from numpy import argmax
pred = [argmax(_p) for _p in y_hat]
print("test samples length={}".format(len(pred)))
accuracy=sum([1 if _p==_r else 0 for _p,_r in zip(pred,y_test)])/len(pred)
print("accuracy= %.2f%%" %accuracy*100)

(60, 3)
test samples length=60
accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy= 0.27%accuracy=

In [170]:
y_hat=load_bst.predict(x_test,num_iteration=99)
print(y_hat.shape)
from numpy import argmax
pred = [argmax(_p) for _p in y_hat]
print("test samples length={}".format(len(pred)))
accuracy=sum([1 if _p==_r else 0 for _p,_r in zip(pred,y_test)])/len(pred)
print("accuracy= %.2f%%" %(accuracy*100))

(60, 3)
test samples length=60
accuracy= 26.67%


In [171]:
load_bst.params

{'objective': 'multiclass',
 'num_class': 3,
 'metric': 'multi_logloss',
 'learning_rate': 0.05}

In [172]:
load_bst.update(train_set=cv_train)

False

In [173]:
y_hat=load_bst.predict(x_test,num_iteration=99)
print(y_hat.shape)
from numpy import argmax
pred = [argmax(_p) for _p in y_hat]
print("test samples length={}".format(len(pred)))
accuracy=sum([1 if _p==_r else 0 for _p,_r in zip(pred,y_test)])/len(pred)
print("accuracy= %.2f%%" %(accuracy*100))

(60, 3)
test samples length=60
accuracy= 26.67%


In [174]:
from sklearn.externals import joblib

In [175]:
joblib.dump(bst,"booster.pkl")

['booster.pkl']

In [176]:
bst_job=joblib.load("booster.pkl")

In [177]:
y_hat=bst_job.predict(x_test,num_iteration=99)
print(y_hat.shape)
from numpy import argmax
pred = [argmax(_p) for _p in y_hat]
print("test samples length={}".format(len(pred)))
accuracy=sum([1 if _p==_r else 0 for _p,_r in zip(pred,y_test)])/len(pred)
print("accuracy= %.2f%%" %(accuracy*100))

(60, 3)
test samples length=60
accuracy= 91.67%


In [178]:
load_bst.current_iteration

<bound method Booster.current_iteration of <lightgbm.basic.Booster object at 0x000001B7B6E8E7F0>>

In [179]:
load_bst.update(train_set=cv_train)

False

In [180]:
load_bst.update(train_set=cv_train)

False

In [181]:
y_hat=load_bst.predict(x_test,num_iteration=99)
print(y_hat.shape)
from numpy import argmax
pred = [argmax(_p) for _p in y_hat]
print("test samples length={}".format(len(pred)))
accuracy=sum([1 if _p==_r else 0 for _p,_r in zip(pred,y_test)])/len(pred)
print("accuracy= %.2f%%" %(accuracy*100))

(60, 3)
test samples length=60
accuracy= 91.67%


In [183]:
bst_init=lgb.Booster(model_file="iris_model.txt")

In [184]:
bst_init.params

{}

In [185]:
y_hat=bst_init.predict(x_test,num_iteration=99)
print(y_hat.shape)
from numpy import argmax
pred = [argmax(_p) for _p in y_hat]
print("test samples length={}".format(len(pred)))
accuracy=sum([1 if _p==_r else 0 for _p,_r in zip(pred,y_test)])/len(pred)
print("accuracy= %.2f%%" %(accuracy*100))

(60, 3)
test samples length=60
accuracy= 91.67%


In [186]:
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
'''
@File    :   df_demo.py
@Time    :   2019/06/28 23:29:25
@Author  :   Jin Weihua 
@Version :   1.0
@Contact :   jwhV587@gmail.com
@License :   (C)Copyright 2017-2018, Liugroup-NLPR-CASIA
@Desc    :   None
'''

# here put the import lib
import pandas as pd
from numpy import arange,random
from copy import copy,deepcopy

_data = arange(0,9)
_data = _data.reshape(3,3)
_col = ["a","b","c"]
_df = pd.DataFrame(_data,columns=_col)
print("now df\n",_df)
_df_cpy = copy(_df)
print("_df id=",id(_df))
print("_df_cpy id=",id(_df_cpy))
random.shuffle(_df.values)
print("current df\n",_df)



now df
    a  b  c
0  0  1  2
1  3  4  5
2  6  7  8
_df id= 1888569001632
_df_cpy id= 1888556939136
current df
    a  b  c
0  0  1  2
1  3  4  5
2  6  7  8


In [187]:
print(_df_cpy)



   a  b  c
0  0  1  2
1  3  4  5
2  6  7  8


In [188]:
_df_cpy.columns



Index(['a', 'b', 'c'], dtype='object')

In [189]:
_df["d"]=[None,0,0]



In [190]:
def fill_na(row):
    if row["d"]:
        row["d"] += 1
    else:
        row["d"] = 0
    return row



In [191]:
get_ipython().run_line_magic('pinfo', 'fill_na')



In [192]:
_df.apply(fill_na,axis=1)



a    b    c    d
0  0.0  1.0  2.0  NaN
1  3.0  4.0  5.0  0.0
2  6.0  7.0  8.0  0.0

In [193]:
_df



a  b  c    d
0  0  1  2  NaN
1  3  4  5  0.0
2  6  7  8  0.0

In [194]:
def fill_na(row):
    
    row["d"] += 1
    return row



In [195]:
_df.apply(fill_na,axis=1)



a    b    c    d
0  0.0  1.0  2.0  NaN
1  3.0  4.0  5.0  1.0
2  6.0  7.0  8.0  1.0

In [196]:
def fill_na(row):
    if not row[0]:
        row[0] = 0
    return row



In [197]:
_df.apply(fill_na,axis=1)



a    b    c    d
0  0.0  1.0  2.0  NaN
1  3.0  4.0  5.0  0.0
2  6.0  7.0  8.0  0.0

In [198]:
_df.apply(fill_na,axis=0)



D:\Anaconda2\envs\py3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


a  b  c    d
0  0  1  2  NaN
1  3  4  5  0.0
2  6  7  8  0.0

In [199]:
def add_col(row):
    row["e"] = row["a"] + row["b"]
    return row



In [200]:
_df.apply(fill_na,axis=1)



a    b    c    d
0  0.0  1.0  2.0  NaN
1  3.0  4.0  5.0  0.0
2  6.0  7.0  8.0  0.0

In [201]:
def add_col(row):
    row["e"] = row["a"] + row["b"]
    



In [202]:
add_func=lambda x: x[0]+x[1]



In [203]:
_df.apply(add_func,axis=1)



0     1.0
1     7.0
2    13.0
dtype: float64

In [204]:
add_func=lambda x: x["a"]+x["b"]



In [205]:
_df.apply(add_func,axis=1)



0     1.0
1     7.0
2    13.0
dtype: float64

In [206]:
_df



a  b  c    d
0  0  1  2  NaN
1  3  4  5  0.0
2  6  7  8  0.0

In [207]:
def add_col(row):
    row["e"] = row[0] + row[1]
    return row
    



In [208]:
_df.apply(add_func,axis=1)



0     1.0
1     7.0
2    13.0
dtype: float64

In [209]:
_df.apply(add_col,axis=1)



a    b    c    d     e
0  0.0  1.0  2.0  NaN   1.0
1  3.0  4.0  5.0  0.0   7.0
2  6.0  7.0  8.0  0.0  13.0

In [210]:
def add_col(row):
    row["e"] = row["a"] + row["b"]
    return row
    



In [211]:
_df.apply(add_col,axis=1)



a    b    c    d     e
0  0.0  1.0  2.0  NaN   1.0
1  3.0  4.0  5.0  0.0   7.0
2  6.0  7.0  8.0  0.0  13.0

In [212]:
fill_na



<function __main__.fill_na(row)>

In [213]:
def fill_na(row):
    if row["d"]==0:
        row["d"] += 1
    else:
        row["d"]=0
    return row



In [214]:
_df.apply(fill_na,axis=1)



a    b    c    d
0  0.0  1.0  2.0  0.0
1  3.0  4.0  5.0  1.0
2  6.0  7.0  8.0  1.0

In [215]:
from numpy import NaN



In [216]:
def fill_na(row):
    if row["d"] == NaN or row["d"] is None:
        row["d"] = 0
    else:
        row["d"]=1
    return row



In [217]:
_df.apply(fill_na,axis=1)



a    b    c    d
0  0.0  1.0  2.0  1.0
1  3.0  4.0  5.0  1.0
2  6.0  7.0  8.0  1.0

In [218]:
_df



a  b  c    d
0  0  1  2  NaN
1  3  4  5  0.0
2  6  7  8  0.0

In [219]:
_df.d[0]



nan

In [220]:
if _df.d[0] is NaN:
    print(1)



In [221]:
type(_df.d[0])



numpy.float64

In [222]:
type(NaN)



float

In [223]:
type(_df.d[1])



numpy.float64

In [224]:
if not _df.d[0]:
    print(1)



In [225]:
if not _df.d[1]:
    print(1)



1


In [226]:
if _df.d[0]:
    print(1)



1


In [227]:
if _df.d[0] is None:
    print(1)
    



In [228]:
sum(_df["d"].values)



nan

In [229]:
for v in _df["d"]:
    if v is None:
        print("y")



In [230]:
for v in _df["d"].values:
    if v is None:
        print("y")



In [231]:
_df["d"].values



array([nan,  0.,  0.])

In [232]:
from numpy import isnan



In [233]:
for v in _df["d"].values:
    if isnan(v):
        print("y")



y


In [234]:
from numpy import inf



In [235]:
if isnan(inf):
    print(1)



In [236]:
_df_add=_df.apply(add_col,axis=1)



In [237]:
_df_add



a    b    c    d     e
0  0.0  1.0  2.0  NaN   1.0
1  3.0  4.0  5.0  0.0   7.0
2  6.0  7.0  8.0  0.0  13.0

In [238]:
from numpy import cast



In [239]:
def fill_na(row):
    if isnan(row["d"]):
        row["d"] = 0
    else:
        row["d"]=1
    return row



In [240]:
_df.apply(fill_na,axis=1)



a    b    c    d
0  0.0  1.0  2.0  0.0
1  3.0  4.0  5.0  1.0
2  6.0  7.0  8.0  1.0

In [241]:
_df["e"]=['1','2','ww']



In [242]:
from pandas import to_numeric



In [243]:
to_numeric(_df["e"],errors="ignore")



0     1
1     2
2    ww
Name: e, dtype: object

In [244]:
to_numeric(_df["e"],errors="cores")



0    1.0
1    2.0
2    NaN
Name: e, dtype: float64

In [245]:
_df.a.astype(int)



0    0
1    3
2    6
Name: a, dtype: int32

In [246]:
_df.a.astype(int,inplace=True)



0    0
1    3
2    6
Name: a, dtype: int32

In [247]:
_df



a  b  c    d   e
0  0  1  2  NaN   1
1  3  4  5  0.0   2
2  6  7  8  0.0  ww

In [248]:
_df_add.a.astype(int,inplace=True)



0    0
1    3
2    6
Name: a, dtype: int32

In [249]:
_df_add



a    b    c    d     e
0  0.0  1.0  2.0  NaN   1.0
1  3.0  4.0  5.0  0.0   7.0
2  6.0  7.0  8.0  0.0  13.0

In [250]:
_df_add["a"]=_df_add.a.astype(int,inplace=True)



In [251]:
_df_add



a    b    c    d     e
0  0  1.0  2.0  NaN   1.0
1  3  4.0  5.0  0.0   7.0
2  6  7.0  8.0  0.0  13.0

In [252]:
_df.a



0    0
1    3
2    6
Name: a, dtype: int32

In [253]:
_df_add.a



0    0
1    3
2    6
Name: a, dtype: int32

In [254]:
from sklearn.datasets import load_iris



In [255]:
iris=load_iris()



In [256]:
iris.keys



<function Bunch.keys>

In [257]:
iris.data



array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [258]:
iris.feature_names



['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [259]:
iris.target



array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [260]:
iris.target_names



array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [261]:
from sklearn.model_selection import train_test_split



In [262]:
x_train,x_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.4,random_state=0)

